<?php

use Illuminate\Database\Seeder;
use App\Models\Course;

class CoursesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
				DB::table('courses')->truncate();

        $courses = $this->getCourses();
				Course::insert($courses);

        DB::statement("UPDATE courses SET code = UPPER(substring(MD5(RAND()),1,5))");
        DB::statement("UPDATE courses SET code = 'ABC' WHERE ID = 1");
    }

		public function getCourses(){

			return Array(
				["city" => "Pleasantville", "name" => "ABC Meadows"],
				["city" => "Caistorville", "name" => "Caistorville Golf Club"],
				["city" => "Calabogie", "name" => "Calabogie Highlands Golf Resort"],
				["city" => "Erin", "name" => "Calerin Golf Club"],
				["city" => "Cambridge", "name" => "Cambridge Golf Club"],
				["city" => "Odessa", "name" => "Camden Braes Golf & Country Club"],
				["city" => "Cumberland", "name" => "Camelot Golf & Country Club"],
				["city" => "Camlachie", "name" => "Camlachie Golf & Country Club"],
				["city" => "Ashton", "name" => "Canadian Golf and Country Club"],
				["city" => "Beeton, Ontario", "name" => "Canadiana Country Club"],
				["city" => "Gloucester", "name" => "Capital Golf Centre"],
				["city" => "Strathroy", "name" => "Caradoc Sands Golf Course"],
				["city" => "Welland", "name" => "Cardinal Lakes Golf Club"],
				["city" => "Caledon", "name" => "Caledon Country Club"],
				["city" => "Bolton", "name" => "Caledon Woods Golf Club"],
				["city" => "Burlington", "name" => "Camisle Golf"],
				["city" => "King", "name" => "Cardinal Golf Club"],
				["city" => "Maple", "name" => "Carrickmacross Golf Centre"],
				["city" => "Manotick", "name" => "Carleton Golf & Yacht Club"],
				["city" => "Carleton Place", "name" => "Carlbeck Golf & Country Club"],
				["city" => "Carlisle", "name" => "Carlisle Golf And Country Club"],
				["city" => "Ajax", "name" => "Carruther’s Creek Golf & Country Club"],
				["city" => "King", "name" => "Carrying Place Golf & Country Club"],
				["city" => "Casselman", "name" => "Casselview Golf & Country Club"],
				["city" => "Kingston", "name" => "Cataraqui Golf and Country Club"],
				["city" => "Cayuga", "name" => "Cayuga Golf Club"],
				["city" => "Scarborough", "name" => "Cedar Brae Golf & Country Club"],
				["city" => "Woodstock", "name" => "Cedar Creek Golf Club"],
				["city" => "Williamsburg", "name" => "Cedar Glen Golf Course"],
				["city" => "Garson", "name" => "Cedar Green Golf Club"],
				["city" => "Barrie", "name" => "Cedar Links Golf Centre"],
				["city" => "Harcourt", "name" => "Cedar Meadow Golf Course"],
				["city" => "Brockville", "name" => "Cedar Valley Golf and Country Club"],
				["city" => "Nepean, Ottawa", "name" => "Cedarhill Golf Club"],
				["city" => "Beaverton", "name" => "Cedarhurst Golf Club"],
				["city" => "Thunder Bay", "name" => "Centennial Golf Course"],
				["city" => "Etobicoke", "name" => "Centennial Park Golf Course"],
				["city" => "Troy", "name" => "Century Pines Golf Club"],
				["city" => "Edwards", "name" => "Champions Nest Golf Club"],
				["city" => "Thunder Bay", "name" => "Chapples Golf Course"],
				["city" => "Hamilton", "name" => "Chedoke Municipal Golf Club"],
				["city" => "Chelmsford", "name" => "Chelmsford Golf Course"],
				["city" => "Pickering", "name" => "Cherry Downs Golf Club"],
				["city" => "Ridgeway", "name" => "Cherry Hill Club"],
				["city" => "Allenford", "name" => "Chesley Lake Camp Golf Course"],
				["city" => "Mount Hope, Hamilton", "name" => "Chippewa Creek Golf & Country Club"],
				["city" => "Chisholm", "name" => "Clear Springs Golf Course"],
				["city" => "Winchester", "name" => "Cloverdale Links Golf Club"],
				["city" => "Bond Head", "name" => "Club at Bond Head"],
				["city" => "Georgetown", "name" => "The Club at North Halton"],
				["city" => "Port Elgin", "name" => "The Club at Westlinks"],
				["city" => "Hearst", "name" => "Club de Golf de Hearst"],
				["city" => "Wallaceburg", "name" => "The Clubhouse at Baldoon"],
				["city" => "Kemble", "name" => "Cobble Beach Golf Links"],
				["city" => "Thamesford", "name" => "Cobble Hills Golf Club"],
				["city" => "Coburg", "name" => "Cobourg Creek Golf Course"],
				["city" => "Chelmsford", "name" => "Colonial Golf Course"],
				["city" => "Joyceville", "name" => "Colonnade Golf & Country Club"],
				["city" => "Oshawa", "name" => "Columbus Golf & Country Club"],
				["city" => "Conestogo", "name" => "Conestoga Golf and Conference Centre"],
				["city" => "Kleinburg", "name" => "Copper Creek Golf Club"],
				["city" => "Uxbridge", "name" => "Coppinwood Golf Club"],
				["city" => "Copetown, Hamilton", "name" => "Copetown Woods Golf Club"],
				["city" => "Woodlawn, Ottawa", "name" => "Copperdale Golf Club"],
				["city" => "Tobermory", "name" => "Cornerstone Golf Club"],
				["city" => "Cornwall", "name" => "Cornwall Golf and Country Club"],
				["city" => "Orillia", "name" => "Couchiching Golf & Country Club"],
				["city" => "Woodbridge", "name" => "The Country Club"],
				["city" => "Dover Centre", "name" => "Country View Golf Course"],
				["city" => "Woodstock", "name" => "Craigowan Golf Club"],
				["city" => "Collingwood", "name" => "Cranberry Golf Course"],
				["city" => "Mississauga", "name" => "Credit Valley Golf & Country Club"],
				["city" => "Woodstock", "name" => "Creekside Golf Club"],
				["city" => "Markham", "name" => "Cresthaven Golf Club"],
				["city" => "Manilla", "name" => "Crestwood Golf Club"],
				["city" => "Sault Ste. Marie", "name" => "Crimson Ridge Golf Resort"],
				["city" => "Athens", "name" => "Crooked Creek Golf Course"],
				["city" => "Burlington", "name" => "Crosswinds Golf & Country Club"],
				["city" => "London", "name" => "Crumlin Creek Golf Club"],
				["city" => "Curran", "name" => "Curran Par-3 Golf Club"],
				["city" => "Guelph", "name" => "Cutten Fields"],
				["city" => "Coburg", "name" => "Dalewood Golf Club"],
				["city" => "Deep River, Ontario", "name" => "Deep River Golf Club"],
				["city" => "Huntsville", "name" => "Deerhurst Higlands Golf Course"],
				["city" => "Huntsville", "name" => "Deerhurst Lakeside Golf Course"],
				["city" => "Ajax", "name" => "Deer Creek Golf"],
				["city" => "Kitchener", "name" => "Deer Ridge Golf Club"],
				["city" => "Blenheim", "name" => "Deer Run Golf Club"],
				["city" => "Parry Sound", "name" => "Deer Run Golf Course"],
				["city" => "Little Britain", "name" => "Deer Run Golf Course at Kawartha Lakes"],
				["city" => "Oakville", "name" => "Deerfield Golf Club"],
				["city" => "Scarborough", "name" => "Dentonia Park Golf Course"],
				["city" => "Mississauga", "name" => "Derrydale Golf Course"],
				["city" => "Delhi", "name" => "Delhi Golf & Country Club"],
				["city" => "Caledon East", "name" => "Devil's Paintbrush Golf Course"],
				["city" => "Caledon", "name" => "Devil's Pulpit Golf Course"],
				["city" => "Utterson", "name" => "The Diamond in the Ruff"],
				["city" => "Richmond Hill", "name" => "DiamondBack Golf Club"],
				["city" => "Utterson", "name" => "Diamond in The Ruff Golf Club"],
				["city" => "Oldcastle", "name" => "Dominion Golf & Country Club"],
				["city" => "Toronto", "name" => "Don Valley Golf Course"],
				["city" => "Toronto", "name" => "Donalda Club"],
				["city" => "Smith Falls", "name" => "Donneybrooke Golf Club"],
				["city" => "Kitchener", "name" => "Doon Valley Golf Course"],
				["city" => "Dorchester", "name" => "Dorchester Golf Club"],
				["city" => "Thunder Bay", "name" => "Dragon Hills Golf Course"],
				["city" => "Flamborough", "name" => "Dragon's Fire Golf Club"],
				["city" => "Renfrew", "name" => "Dragonfly Golf Links"],
				["city" => "Orangeville", "name" => "Dufferin Glen Golf Club"],
				["city" => "Dundas", "name" => "Dundas Valley Golf & Curling Club Ltd."],
				["city" => "New Dundee", "name" => "Dundee Golf Club"],
				["city" => "Dundalk", "name" => "Dunadel Golf Association"],
				["city" => "Dunnville", "name" => "Dunnville Golf & Country Club"],
				["city" => "Dunsford", "name" => "Dunsford Golf & Country Club"],
				["city" => "Duntroon", "name" => "Duntroon Highlands Golf Club"],
				["city" => "Dutton", "name" => "Dutton Meadows Golf Club"],
				["city" => "Dunrobin", "name" => "Eagle Creek Golf Club"],
				["city" => "South River", "name" => "Eagle Lake Golf Course"],
				["city" => "Georgetown", "name" => "Eagle Ridge Golf Club"],
				["city" => "Niagara Falls", "name" => "Eagle Valley Golf Club"],
				["city" => "Oxdrift", "name" => "Eagles' Landing Golf Course"],
				["city" => "Maple", "name" => "Eagles Nest Golf Club"],
				["city" => "Ear Falls", "name" => "Ear Falls Municipal Golf Course"],
				["city" => "London", "name" => "East Park London"],
				["city" => "Keswick", "name" => "The Eastbourne Golf Club"],
				["city" => "London", "name" => "Echo Valley Golf Course"],
				["city" => "Eden", "name" => "Eden Golf Club"],
				["city" => "Woodlawn, Ottawa", "name" => "Edgewood Links of Woodlawn"],
				["city" => "Leamington", "name" => "Erie Shores Golf & Country Club"],
				["city" => "Fenelon Falls", "name" => "Eganridge Inn & Country Club"],
				["city" => "Whitby", "name" => "Eldorado Golf Club"],
				["city" => "Elmira", "name" => "Elmira Golf Club"],
				["city" => "Thunder Bay", "name" => "Emerald Greens Golf Course"],
				["city" => "Stouffville", "name" => "Emerald Hills Golf Club"],
				["city" => "Greely, Ottawa", "name" => "Emerald Links Golf & Country Club"],
				["city" => "York", "name" => "Empire Springs Golf Club"],
				["city" => "Kemptville", "name" => "eQuinelle Golf Club"],
				["city" => "Erin", "name" => "Erin Heights Golf Club"],
				["city" => "Espanola", "name" => "Espanola Golf & Country Club"],
				["city" => "LaSalle", "name" => "Essex Golf & Country Club"],
				["city" => "Washago", "name" => "Evergreen Golf Centre"],
				["city" => "Westport", "name" => "Evergreen Golf Course"],
				["city" => "Exeter", "name" => "Exeter Golf Club"],
				["city" => "Bracebridge", "name" => "The Fairways at Kirrie Glen"],
				["city" => "St. Catherines", "name" => "Fairview Golf Course"],
				["city" => "Gloucester", "name" => "Falcon Ridge Golf Club"],
				["city" => "London", "name" => "Fanshawe Golf Course"],
				["city" => "Fergus", "name" => "Fergus Golf Club"],
				["city" => "Scotland", "name" => "Fescue’s Edge Golf Course"],
				["city" => "West Grey", "name" => "Ferns Golf Course"],
				["city" => "Komoka", "name" => "FireRock Golf Club"],
				["city" => "Copetown", "name" => "Flamborough Hills Golf & Country Club"],
				["city" => "Toronto", "name" => "Flemingdon Park Golf Club"],
				["city" => "London", "name" => "Forest City National Golf Club"],
				["city" => "Forest", "name" => "Forest Golf Club & Inn"],
				["city" => "Chelmsford", "name" => "Forest Ridge Country Club"],
				["city" => "Fort Erie", "name" => "Fort Erie Golf Club"],
				["city" => "Thunder Bay", "name" => "Fort William Country Club"],
				["city" => "Granton", "name" => "The Fox Golf Club"],
				["city" => "McGregor", "name" => "Fox Glen Golf Club"],
				["city" => "Fonthill", "name" => "Fox Run Golf Course"],
				["city" => "Uxbridge", "name" => "Foxbridge Golf & Country Club"],
				["city" => "Baden", "name" => "Foxwood Country Club"],
				["city" => "Frankford", "name" => "Frankford Golf Course"],
				["city" => "Dunnville", "name" => "Freedom Oaks Golf Club"],
				["city" => "Alban", "name" => "French River Golf Resort"],
				["city" => "Cambridge", "name" => "Galt Country Club"],
				["city" => "Gananoque", "name" => "Gananoque Golf & Country Club"],
				["city" => "St. Catherines", "name" => "Garden City Golf Course"],
				["city" => "Kingston", "name" => "Garrison Golf and Curling Club"],
				["city" => "Melbourne", "name" => "Gentleman Creek Golf Course"],
				["city" => "Clarksburg", "name" => "The Georgian Bay Club"],
				["city" => "Oakville", "name" => "Glen Abbey Golf Course"],
				["city" => "Pickering", "name" => "Glen Cedars Golf Club"],
				["city" => "Caledon", "name" => "Glen Eagle Golf Club"],
				["city" => "Kingston", "name" => "Glen Lawrence Golf Club"],
				["city" => "Halton Hills", "name" => "Glencairn Golf Club"],
				["city" => "King City", "name" => "Glendale Golf & Country Club"],
				["city" => "Alexandria", "name" => "Glengarry Golf Club"],
				["city" => "Goderich", "name" => "Goderich Sunset Golf Club"],
				["city" => "Port Perry", "name" => "Golfer's Dream Golf Club"],
				["city" => "Thornbury", "name" => "The Golf Club at Lora Bay"],
				["city" => "Gravenhurst", "name" => "Gravenhurst / Muskoka KOA Golf Course"],
				["city" => "Mississauga", "name" => "Grand Highland Golf Club"],
				["city" => "Niagara Falls", "name" => "Grand Niagara Golf Club"],
				["city" => "Cambridge", "name" => "Grand Valley Golf & Country Club"],
				["city" => "Huntsville", "name" => "Grandview Golf Club"],
				["city" => "Whitchurch-Stouffville", "name" => "Granite Golf Club"],
				["city" => "Milton", "name" => "Granite Ridge Golf Club"],
				["city" => "Welland", "name" => "Grassy Brook Golf Course"],
				["city" => "Gananoque", "name" => "Greene Acre Golf Club"],
				["city" => "Angus", "name" => "Green Acres Golf Centre"],
				["city" => "London", "name" => "Greenhills Golf Club"],
				["city" => "Simcoe", "name" => "Greens at Renton"],
				["city" => "Carp", "name" => "Greensmere Golf & Country Club"],
				["city" => "Sarnia", "name" => "Greenwood Golf Course"],
				["city" => "Brockville", "name" => "Grenadier Island Country Club"],
				["city" => "Cumberland", "name" => "GreyHawk Golf Club"],
				["city" => "Waterloo", "name" => "Grey Silo Golf Club"],
				["city" => "Milton", "name" => "Greystone Golf Club"],
				["city" => "Sarnia", "name" => "Greystone Golf Course"],
				["city" => "Guelph", "name" => "Guelph Country Club"],
				["city" => "Guelph", "name" => "Guelph Lakes Golf & Country Club"],
				["city" => "Haileybury", "name" => "Haileybury Golf Club"],
				["city" => "Haliburton", "name" => "Haliburton Highlands Golf Course"],
				["city" => "Milton", "name" => "Halton Country Golf & Banquet Hall"],
				["city" => "Lakefield", "name" => "Hamilton Bay Golf Course"],
				["city" => "Ancaster, Hamilton", "name" => "Hamilton Golf and Country Club"],
				["city" => "Hammond", "name" => "Hammond Golf and Country Club"],
				["city" => "Embro", "name" => "Happy Hills Resort"],
				["city" => "Gilford", "name" => "Harbour View Golf & Country Club"],
				["city" => "Oshawa", "name" => "Harmony Creek Golf Club"],
				["city" => "Orillia", "name" => "Hawk Ridge Golf & Country Club"],
				["city" => "Hawkesbury", "name" => "Hawkesbury Golf & Curling Club"],
				["city" => "Pickering", "name" => "Hawthorne Valley Golf Course"],
				["city" => "Hearst", "name" => "Hearst Golf Club"],
				["city" => "Lancaster", "name" => "Héritage Golf"],
				["city" => "Petrolia", "name" => "Heritage Heights Golf & Curling Club"],
				["city" => "Shanty Bay", "name" => "Heritage Hills Golf Club"],
				["city" => "Niagara-on-the-Lake", "name" => "Heritage Woods Golf Course"],
				["city" => "Cavan Monaghan", "name" => "Heron Landing Golf Course"],
				["city" => "Alberton", "name" => "Heron Point Golf Links"],
				["city" => "London", "name" => "Hickory Ridge Golf and Country Club"],
				["city" => "Burlington", "name" => "Hidden Lake Golf Club"],
				["city" => "London", "name" => "Highland Country Club"],
				["city" => "Priceville", "name" => "Highland Glen Golf Club"],
				["city" => "Powassan", "name" => "Highview Golf Course"],
				["city" => "Mono", "name" => "Hockley Valley Resort"],
				["city" => "Alban", "name" => "Holiday Golf & Country Club"],
				["city" => "Port Elgin", "name" => "Holiday Golf Club"],
				["city" => "Sarnia", "name" => "Holiday Inn Golf Course"],
				["city" => "Timmins", "name" => "Hollinger Golf Club"],
				["city" => "Durham", "name" => "The Homestead Golf & Winter Resort"],
				["city" => "Barrie", "name" => "Horseshoe Resort"],
				["city" => "Halton Hills", "name" => "Hornby Glen Golf Course"],
				["city" => "Toronto", "name" => "Humber Valley Golf Course"],
				["city" => "Cloyne", "name" => "Hunter's Creek Golf Course"],
				["city" => "Welland", "name" => "Hunters Pointe Golf Course"],
				["city" => "Huntsville", "name" => "Huntsville Downs Golf Course"],
				["city" => "Brights Grove, Sarnia", "name" => "Huron Oaks Golf Course"],
				["city" => "Blind River", "name" => "Huron Pines Golf & Country Club"],
				["city" => "Ashburn", "name" => "Hy-Hope Golf Course"],
				["city" => "Gloucester", "name" => "Hylands Golf Club"],
				["city" => "Ignace", "name" => "Ignace Golf & Country Club"],
				["city" => "Sudbury", "name" => "Ildylwylde Golf & Country Club"],
				["city" => "Lambton Shores", "name" => "Indian Hills Golf Club"],
				["city" => "Pembroke", "name" => "Indian River Golf Club"],
				["city" => "Burlington", "name" => "Indian Wells Golf Club"],
				["city" => "Ingersoll", "name" => "Ingersoll Golf Club"],
				["city" => "Innerkip", "name" => "Innerkip Highlands Golf Club"],
				["city" => "Cookstown, Ontario", "name" => "Innisfil Creek Golf Club"],
				["city" => "Barrie", "name" => "Innisbrook Golf & Country Club"],
				["city" => "Stevensville", "name" => "International Country Club of Niagara"],
				["city" => "Inverary", "name" => "Inverary Golf Courses"],
				["city" => "Carp", "name" => "Irish Hills Golf Club"],
				["city" => "Orangeville, Ontario", "name" => "Iron & the Eagle Golf & Country Club"],
				["city" => "Exeter", "name" => "Ironwood Golf Club"],
				["city" => "Iroquois", "name" => "Iroquois Golf Club"],
				["city" => "St. Joseph Island", "name" => "Island Springs Golf Resort"],
				["city" => "Islington–City Centre West, Etobicoke", "name" => "Islington Golf Club"],
				["city" => "Smith Falls", "name" => "Juniper Fairways Golf Club"],
				["city" => "Kanata, Ottawa", "name" => "Kanata Golf Club"],
				["city" => "Kapuskasing", "name" => "Kapuskasing Golf Club"],
				["city" => "Lakefield", "name" => "Katchiwano Golf & Country Club"],
				["city" => "Chapleau", "name" => "Kebsquaheshing Golf Club"],
				["city" => "Oshawa", "name" => "Kedron Dells Golf Course"],
				["city" => "Geraldton", "name" => "Kenogamisis Golf Club"],
				["city" => "Cavan Monaghan", "name" => "Keystone Links Golf & Country Club"],
				["city" => "Kincardine", "name" => "Kincardine Golf & Country Club"],
				["city" => "Kenora", "name" => "Kenora Golf & Country Club"],
				["city" => "Port Stanley", "name" => "Kettle Creek Golf & Country Club"],
				["city" => "Seagrave", "name" => "King's Bay Golf Club"],
				["city" => "Hamilton", "name" => "King's Forest Golf Course"],
				["city" => "King City", "name" => "King's Riding Golf Club"],
				["city" => "King City", "name" => "King Valley Golf Club"],
				["city" => "Kingston", "name" => "Kingston Fairways"],
				["city" => "Kingsville", "name" => "Kingsville Golf & Country Club"],
				["city" => "Kirkland Lake", "name" => "Kirkland Lake Golf Club"],
				["city" => "Fort Frances", "name" => "Kitchen Creek Golf Course"],
				["city" => "Ancaster, Hamilton", "name" => "Knollwood Golf Club"],
				["city" => "Peterborough", "name" => "Kawartha Golf & Country Club"],
				["city" => "Hawkesbury", "name" => "La Cité Golf Club"],
				["city" => "Thornhill", "name" => "Ladies' Golf Club of Toronto"],
				["city" => "Port Carling", "name" => "The Lake Joseph Club"],
				["city" => "Orillia", "name" => "Lake Saint George Golf & Country Club"],
				["city" => "Washago", "name" => "Lake St. George Golf Club"],
				["city" => "Brooklin, Whitby", "name" => "Lakeridge Links Golf Club"],
				["city" => "West Guilford", "name" => "Lakeside Golf Club"],
				["city" => "Mississauga", "name" => "Lakeview Golf Course"],
				["city" => "Jackson's Point", "name" => "Lakeview House Golf Course"],
				["city" => "Kingston", "name" => "Landings Golf Course & Teaching Centre"],
				["city" => "Barrie", "name" => "Landings of Willow Creek Golf Course"],
				["city" => "Toronto", "name" => "Lambton Golf and Country Club"],
				["city" => "Sturgeon Falls", "name" => "Laurentide Golf Club"],
				["city" => "Cloyne", "name" => "Lazz Golf and Country Club"],
				["city" => "Aurora", "name" => "Lebovic Golf Club"],
				["city" => "Cochrane", "name" => "Lee Golf Club"],
				["city" => "Owen Sound", "name" => "Legacy Ridge Golf Club"],
				["city" => "Niagara Falls", "name" => "Legends on the Niagara"],
				["city" => "Peterborough", "name" => "The Liftlock Golf Club"],
				["city" => "Wasaga Beach", "name" => "The Links at Georgian Sands"],
				["city" => "Norland", "name" => "The Links at Monck's Landing Golf Club"],
				["city" => "Brampton", "name" => "Lionhead Golf & Conference Centre"],
				["city" => "Listowel", "name" => "Listowel Golf Club"],
				["city" => "Atikokan", "name" => "Little Falls Golf Club"],
				["city" => "Windsor", "name" => "Little River Golf Course"],
				["city" => "Lindsay", "name" => "Lindsay Golf & Country Club"],
				["city" => "Chatham", "name" => "Links Kent Golf Club"],
				["city" => "Thessalon", "name" => "Livingstone Creek Golf Course"],
				["city" => "Lively", "name" => "Lively Golf Club"],
				["city" => "Arva", "name" => "Llyndinshire Golf & Country Club"],
				["city" => "Kanata", "name" => "Loch March Golf & Country Club"],
				["city" => "Lombardy", "name" => "Lombard Glen Golf Club"],
				["city" => "London", "name" => "London Hunt & Country Club"],
				["city" => "Wainfleet", "name" => "Long Beach Country Club"],
				["city" => "Fonthill", "name" => "Lookout Point Golf Club"],
				["city" => "Burlington", "name" => "Lowville Golf Club"],
				["city" => "Bath", "name" => "Loyalist Golf and Country Club"],
				["city" => "Amaranth", "name" => "Lynbrook Family Golf Centre"],
				["city" => "Whitby", "name" => "Lyndebrook Golf Course"],
				["city" => "Baldwin", "name" => "Lyndhurst Golf Course"],
				["city" => "Lyndhurst", "name" => "Lyndway Hills Golf Course"],
				["city" => "Port Dover", "name" => "Lynn Meadows Golf & Country Club"],
				["city" => "Arnprior", "name" => "Madawaska Golf Club"],
				["city" => "Creemore", "name" => "Mad River Golf Club"],
				["city" => "Aurora", "name" => "Magna Golf Club"],
				["city" => "Goderich", "name" => "The Maitland"],
				["city" => "Markham", "name" => "Mandarin Golf & Country Club"],
				["city" => "North Gower", "name" => "Manderley on the Green"],
				["city" => "Gore Bay", "name" => "Manitoulin Island Country Club"],
				["city" => "Manitouwadge", "name" => "Manitouwadge Municipal Golf Course"],
				["city" => "Chatham", "name" => "Maple City Country Club"],
				["city" => "Maple", "name" => "Maple Downs Golf & Country Club"],
				["city" => "Minett", "name" => "Maple Hills Golf Course"],
				["city" => "London", "name" => "Maple Ridge Golf Club"],
				["city" => "Noëlville", "name" => "The Maples Golf & Sports Club"],
				["city" => "Whitchurch-Stouffville", "name" => "Maples of Ballantrae Golf Club"],
				["city" => "Perth", "name" => "Mapleview Golf Club"],
				["city" => "Sault Ste. Marie", "name" => "Maplewood Golf Course and Driving Range"],
				["city" => "Markdale", "name" => "Markdale Golf & Curling Club"],
				["city" => "Markham", "name" => "Markham Golf & Country Club"],
				["city" => "Markham", "name" => "Markham Green Golf Club"],
				["city" => "Toronto", "name" => "Markland Wood Golf Club"],
				["city" => "Wasaga Beach", "name" => "Marlwood Golf and Country Club"],
				["city" => "Ottawa", "name" => "Marshes Golf Club"],
				["city" => "Dysart and Others", "name" => "MartinWood Resort & Golf Course"],
				["city" => "Apsley", "name" => "Marvel Rapids Golf Course"],
				["city" => "Mattawa", "name" => "Mattawa Golf & Ski Resort"],
				["city" => "Caledon East", "name" => "Mayfield Golf Club"],
				["city" => "Meaford", "name" => "Meaford Golf & Country Club"],
				["city" => "Amaranth", "name" => "Meadow Land Golf Club"],
				["city" => "Monteville", "name" => "Meadow Springs Golf Course"],
				["city" => "Gormley", "name" => "Meadowbrook Golf & Country Club"],
				["city" => "Ottawa", "name" => "The Meadows Golf & Country Club"],
				["city" => "Navan, Ottawa", "name" => "Mer Bleue Golf"],
				["city" => "Breslau", "name" => "Merry-Hill Golf Club"],
				["city" => "Metcalfe", "name" => "Metcalfe Golf Club"],
				["city" => "Wawa", "name" => "Michipicoten Golf Club"],
				["city" => "Midland", "name" => "Midland Golf & Country Club"],
				["city" => "Uxbridge", "name" => "Mill Run Golf Club"],
				["city" => "Burlington", "name" => "Millcroft Golf Club"],
				["city" => "Minaki", "name" => "Minaki Lodge Golf Course"],
				["city" => "Minaki", "name" => "Minaki Resort International Golf Course"],
				["city" => "Mississauga", "name" => "Mississaugua Golf & Country Club"],
				["city" => "Almonte", "name" => "Mississippi Golf Club"],
				["city" => "Mitchell", "name" => "Mitchell Golf & Country Club"],
				["city" => "The Blue Mountains", "name" => "Monterra Golf"],
				["city" => "Val Caron", "name" => "Monte Vista Golf Club"],
				["city" => "Caledonia", "name" => "MontHill Golf and Country Club"],
				["city" => "Moonbeam", "name" => "Moonbeam Golf Club"],
				["city" => "Morrisburg", "name" => "Morrisburg Golf Club"],
				["city" => "Mount Elgin", "name" => "Mount Elgin Golf Club"],
				["city" => "Ayton", "name" => "Mount Forest Golf & Country Club"],
				["city" => "Arnprior", "name" => "Mountain Creek Golf Club"],
				["city" => "Wooler", "name" => "Murray Hills Golf Course"],
				["city" => "Gravenhurst", "name" => "Muskoka Bay Club"],
				["city" => "Bracebridge", "name" => "Muskoka Highlands Golf Links"],
				["city" => "Port Carling", "name" => "Muskoka Lakes Golf & Country Club"],
				["city" => "Foot's Bay", "name" => "Muskoka Woodlands Golf Course and Driving Range"],
				["city" => "Ancaster, Hamilton", "name" => "Mystic Golf Club"],
				["city" => "Curran", "name" => "Nation Golf Club"],
				["city" => "Woodbridge", "name" => "The National Golf Club of Canada"],
				["city" => "South Mountain", "name" => "Nationview Golf Course"],
				["city" => "Napanee", "name" => "Napanee Golf & Country Club"],
				["city" => "Innisfil", "name" => "National Pines Golf Club"],
				["city" => "Dymond", "name" => "New Liskeard Golf Club"],
				["city" => "Newcastle", "name" => "Newcastle Golf & Country Club"],
				["city" => "Niagara-on-the-Lake", "name" => "Niagara-on-the-Lake Golf Club"],
				["city" => "Niagara Falls", "name" => "Niagara Falls Golf Club"],
				["city" => "Nobleton", "name" => "Nobleton Lakes Golf Club"],
				["city" => "Norfolk", "name" => "Norfolk Golf & Country Club"],
				["city" => "North Bay", "name" => "North Bay Golf & Country Club"],
				["city" => "Port Sydney", "name" => "North Granite Ridge Golf Club"],
				["city" => "Nipigon", "name" => "North Shore Golf Course"],
				["city" => "Hepworth", "name" => "Northern Dunes Golf Club"],
				["city" => "Thunder Bay", "name" => "Northern Lights Golf Complex"],
				["city" => "Brantford", "name" => "Northridge Golf Course"],
				["city" => "Alliston", "name" => "Nottawasaga Golf Course"],
				["city" => "Port Severn", "name" => "Oak Bay Golf Club"],
				["city" => "Jerseyville", "name" => "Oak Gables Golf Club"],
				["city" => "Niagara Falls", "name" => "Oak Hall Golf Course"],
				["city" => "Stirling", "name" => "Oak Hills Golf Club"],
				["city" => "Toronto", "name" => "Oakdale Golf & Country Club"],
				["city" => "Asphodel-Norwood", "name" => "Oakland Greens Golf & Country Club"],
				["city" => "Niagara Falls", "name" => "Oaklands Golf Club"],
				["city" => "Port Perry", "name" => "Oakridge Golf Club"],
				["city" => "Oakville", "name" => "Oakville Executive Golf Course"],
				["city" => "Oakville", "name" => "Oakville Golf Club"],
				["city" => "Delaware", "name" => "Oaks Golf & Country Club"],
				["city" => "Cobden", "name" => "Oaks of Cobden Golf Club"],
				["city" => "Paris", "name" => "The Oaks of St. George Golf Club"],
				["city" => "Oakwood", "name" => "Oliver's Nest Golf & Country Club"],
				["city" => "Onaping", "name" => "Onaping Golf & Beach Club"],
				["city" => "Orangeville", "name" => "Orangeville Golf Club"],
				["city" => "Keswick", "name" => "Orchard Beach Golf & Country Club"],
				["city" => "Ruthven", "name" => "Orchard View Golf Course"],
				["city" => "Elmvale", "name" => "Orr Lake Golf Club"],
				["city" => "Oshawa", "name" => "Oshawa Airport Golf Club"],
				["city" => "Oshawa", "name" => "Oshawa Golf & Curling Club"],
				["city" => "Collingwood", "name" => "OslerBrook Golf & Country Club"],
				["city" => "Callander", "name" => "Osprey Links"],
				["city" => "Caledon", "name" => "Osprey Valley Golf"],
				["city" => "Ottawa", "name" => "Ottawa Hunt and Golf Club"],
				["city" => "Otterville", "name" => "Otter Creek Golf Club"],
				["city" => "Forest", "name" => "Our Ponderosa RV & Golf Resort"],
				["city" => "Owenbrook", "name" => "Owenbrook Golf Course"],
				["city" => "Mactier", "name" => "Oviinbyrd Golf Club"],
				["city" => "Komoka", "name" => "Oxbow Glen Golf & Country Club"],
				["city" => "Oxley", "name" => "Oxley Beach Golf Course"],
				["city" => "Pakenham", "name" => "Pakenham Highlands Golf Club"],
				["city" => "Brampton", "name" => "Parkshore Golf Club"],
				["city" => "Parry Sound", "name" => "Parry Sound Golf & Country Club"],
				["city" => "Courtice", "name" => "Pebblestone Golf Course"],
				["city" => "Brampton", "name" => "Peel Village Golf Course"],
				["city" => "Pelham", "name" => "Pelham Hills Golf & Country Club"],
				["city" => "Pembroke", "name" => "Pembroke Golf Club"],
				["city" => "Whitefish", "name" => "Penage Golf Course"],
				["city" => "Marathon", "name" => "Peninsula Golf Course"],
				["city" => "Fenwick", "name" => "Peninsula Lakes Golf Club"],
				["city" => "Perth", "name" => "Perth Golf Course"],
				["city" => "Petawawa", "name" => "Petawawa Golf Club"],
				["city" => "Peterborough", "name" => "Peterborough Golf & Country Club"],
				["city" => "Sharon", "name" => "Pheasant Run Golf Club"],
				["city" => "Pickering", "name" => "Pickering Golf Club"],
				["city" => "Picton", "name" => "Picton Golf & Country Club"],
				["city" => "Clifford", "name" => "Pike Lake Golf Centre Limited"],
				["city" => "Keene", "name" => "Pine Crest Golf & Country Club"],
				["city" => "Sudbury", "name" => "Pine Grove Golf Club"],
				["city" => "Dorchester", "name" => "Pine Knot Golf & Country Club"],
				["city" => "Warkworth", "name" => "Pine Ridge Golf & Country Club"],
				["city" => "Vittoria", "name" => "Pine Valley Golf Club"],
				["city" => "Gloucester", "name" => "Pine View Municipal Golf Course"],
				["city" => "Millgrove", "name" => "Pineland Greens Golf Club"],
				["city" => "Pefferlaw", "name" => "The Pines of Georgina"],
				["city" => "Haliburton", "name" => "Pinestone Resort & Conference Centre"],
				["city" => "North Bay", "name" => "Pinewood Park Golf Club"],
				["city" => "Hepworth", "name" => "Pinewoods Golf Centre"],
				["city" => "Milton", "name" => "Piper's Heath Golf Club"],
				["city" => "St. Thomas", "name" => "Pleasant Valley Golf & Country Club"],
				["city" => "Amherstburg", "name" => "Pointe West Golf Club"],
				["city" => "Tweed", "name" => "Poplars Golf Club"],
				["city" => "Port Carling", "name" => "Port Carling Golf & Country Club"],
				["city" => "Port Colborne", "name" => "Port Colborne Golf & Country Club"],
				["city" => "Port Hope", "name" => "Port Hope Golf & Country Club"],
				["city" => "Prescott", "name" => "Prescott Golf Club"],
				["city" => "Stoney Creek", "name" => "Pros Golf Centre"],
				["city" => "Puslinch", "name" => "Puslinch Lake Golf Course"],
				["city" => "Ennismore", "name" => "Quarry Golf Club"],
				["city" => "Bowmanville", "name" => "Quarry Lakes Golf & Recreation Centre"],
				["city" => "Sault Ste. Marie", "name" => "Queensgate Greens Golf Course"],
				["city" => "Queenston", "name" => "Queenston Golf Club"],
				["city" => "Frankford", "name" => "Quinte Hills Golf Course"],
				["city" => "Manitowaning", "name" => "Rainbow Ridge Golf Course"],
				["city" => "Milton", "name" => "RattleSnake Point Golf Club"],
				["city" => "Petersburg", "name" => "Rebel Creek Golf Club"],
				["city" => "Balmertown", "name" => "Red Lake Golf & Country Club"],
				["city" => "Port Stanley", "name" => "Redtail Golf Course"],
				["city" => "Markham", "name" => "Remington Parkview Golf & Country Club"],
				["city" => "Renfrew", "name" => "Renfrew Golf Club"],
				["city" => "Richmond", "name" => "Richmond Centennial Golf Course"],
				["city" => "Richmond Hill", "name" => "Richmond Hill Golf Club"],
				["city" => "Kemptville", "name" => "Rideau Glen Golf Club"],
				["city" => "Westport", "name" => "Rideau Lakes Golf & Country Club"],
				["city" => "Manotick", "name" => "Rideau View Golf Club"],
				["city" => "McKellar", "name" => "The Ridge at Manitou Golf Club"],
				["city" => "Ridgetown", "name" => "Ridgetown Golf and Curling Club"],
				["city" => "Fort Erie", "name" => "Rio Vista Golf Course"],
				["city" => "Verona", "name" => "Rivendell Golf Club"],
				["city" => "London", "name" => "River Road Golf Course"],
				["city" => "Bancroft", "name" => "River's Edge Golf Course & Country Club Community"],
				["city" => "South Perth", "name" => "River Valley Golf & Country Club"],
				["city" => "London", "name" => "RiverBend Golf Community"],
				["city" => "Richmond", "name" => "Riverbend Golf & Country Club"],
				["city" => "Kitchener", "name" => "RiverEdge Golf Course"],
				["city" => "Ajax", "name" => "Riverside Golf Course"],
				["city" => "Brampton", "name" => "Riverstone Golf & Country Club"],
				["city" => "Pelham", "name" => "Riverview Golf Club"],
				["city" => "Fournier", "name" => "Ridgewood Golf Club"],
				["city" => "Petawawa", "name" => "Roanoke Golf Club"],
				["city" => "Belle River", "name" => "Rochester Place Golf Club & Resort"],
				["city" => "Dundas", "name" => "Rock Chapel Golf Centre"],
				["city" => "Minett", "name" => "The Rock Golf Course"],
				["city" => "Rockland", "name" => "Rockland Golf Club"],
				["city" => "Kitchener", "name" => "Rockway Golf Course"],
				["city" => "St. Catherines", "name" => "Rockway Vineyards Golf Course"],
				["city" => "Mactier", "name" => "Rocky Crest Golf Club"],
				["city" => "Whitchurch-Stouffville", "name" => "Rolling Hills Golf Club"],
				["city" => "Niagara Falls", "name" => "Rolling Meadows Golf & Country Club"],
				["city" => "Toronto", "name" => "Rosedale Golf Club"],
				["city" => "Sault Ste. Marie", "name" => "Root River Golf Club"],
				["city" => "Windsor", "name" => "Roseland Golf Club"],
				["city" => "Astra", "name" => "Roundel Glen Golf Course"],
				["city" => "Coburg", "name" => "Roxburgh Glen Golf Club"],
				["city" => "Whitby", "name" => "Royal Ashburn Golf Club"],
				["city" => "Niagara-on-the-Lake", "name" => "Royal Niagara Golf Club"],
				["city" => "Hornby", "name" => "Royal Ontario Golf Club"],
				["city" => "Toronto", "name" => "Royal Woodbine Golf Club"],
				["city" => "Jarvis", "name" => "Sandusk Golf Club"],
				["city" => "Ajax", "name" => "Salem Ridge Golf & Academy"],
				["city" => "Woodstock", "name" => "Sally Creek Golf Club & Bistro"],
				["city" => "Warkworth", "name" => "Salt Creek Golf Links"],
				["city" => "Lambton Shores", "name" => "Sand Hills Golf Club"],
				["city" => "Braeside", "name" => "Sand Point Golf Course"],
				["city" => "Gravenhurst", "name" => "Sands Golf Club"],
				["city" => "Timmins", "name" => "Sandy Falls Golf Course"],
				["city" => "Mountain", "name" => "Sandy Mountain Golf Course"],
				["city" => "South Mountain", "name" => "Sandy Row Golf Club"],
				["city" => "Sarnia", "name" => "Sarnia Golf & Curling Club"],
				["city" => "Stoney Creek", "name" => "Satellite Golf Club"],
				["city" => "Port Elgin", "name" => "Saugeen Golf Club"],
				["city" => "Sauble Beach", "name" => "Sauble Golf & Country Club"],
				["city" => "Massey", "name" => "Sauble River Golf & Country Club"],
				["city" => "Sault Ste Marie", "name" => "Sault Ste Marie Golf Club"],
				["city" => "Cambridge", "name" => "Savannah Golf Links"],
				["city" => "Camlachie", "name" => "Sawmill Creek Golf Resort & Spa"],
				["city" => "Fenwick", "name" => "Sawmill Golf Course"],
				["city" => "Scarborough", "name" => "Scarboro Golf & Country Club"],
				["city" => "Toronto", "name" => "Scarlett Woods Golf Course"],
				["city" => "Owen Sound", "name" => "Scenic City Golf Course"],
				["city" => "Hannon, Hamilton", "name" => "Scenic Woods Golf Club"],
				["city" => "St. Marys", "name" => "Science Hill Country Club"],
				["city" => "Mississippi Mills", "name" => "Scottish Glen Golf Course"],
				["city" => "Orillia", "name" => "Scottish Highlands Golf Orillia"],
				["city" => "Seaforth", "name" => "Seaforth Golf Club"],
				["city" => "Seguin", "name" => "Seguin Valley Golf & Country Club"],
				["city" => "Elora", "name" => "Senjan Golf Club"],
				["city" => "Grafton", "name" => "Shelter Valley Pines Golf Club"],
				["city" => "Barrie", "name" => "Settlers' Ghost Golf Club"],
				["city" => "LaSalle", "name" => "Seven Lakes Golf Course"],
				["city" => "Shanty Bay", "name" => "Shanty Bay Golf Club"],
				["city" => "Sharon", "name" => "Shawneeki Golf Club"],
				["city" => "Trent Lakes/Bobcaygeon", "name" => "Sheffield Greens Golf Club"],
				["city" => "Melancthon", "name" => "Shelburne Golf & Country Club"],
				["city" => "Lisle", "name" => "Silver Brooke Golf Club"],
				["city" => "Garden River", "name" => "Silver Creek Golf Course"],
				["city" => "East Gwillimbury", "name" => "Silver Lakes Golf & Conference Centre"],
				["city" => "Markstay", "name" => "Silver Styx Golf Course"],
				["city" => "Beaverton", "name" => "Simcoe Shores Golf & Country Club"],
				["city" => "Barrie", "name" => "Simoro Golf Links"],
				["city" => "Sioux Lookout", "name" => "The Sioux Lookout Golf and Curling Club"],
				["city" => "Buckhorn", "name" => "Six Foot Bay Resort & Golf Course"],
				["city" => "Lively", "name" => "Sixth Avenue Golf and Country Club"],
				["city" => "Stouffville", "name" => "Sleepy Hollow Country Club"],
				["city" => "Vineland", "name" => "Sly Fox Golf Club"],
				["city" => "Smith Falls", "name" => "Smiths Falls Golf Club"],
				["city" => "Smooth Rock Falls", "name" => "Smooth Rock Falls Golf Club"],
				["city" => "Lansdowne", "name" => "Smuggler's Glen Golf Course"],
				["city" => "Tiverton", "name" => "Somerhill Golf Club"],
				["city" => "Bracebridge", "name" => "South Muskoka Curling & Golf Club"],
				["city" => "Southampton", "name" => "Southampton Golf & Country Club"],
				["city" => "Mount Hope, Hamilton", "name" => "Southern Pines Golf & Country Club"],
				["city" => "Chatham", "name" => "Southside Tap & Grille"],
				["city" => "Binbrook", "name" => "Southbrook Golf & Country Club"],
				["city" => "Pickering", "name" => "Spring Creek Golf Club"],
				["city" => "Stouffville", "name" => "Spring Lakes Golf Club"],
				["city" => "Guelph", "name" => "Springfield Golf & Country Club"],
				["city" => "Minesing", "name" => "Springwater Golf Course"],
				["city" => "Sleeman", "name" => "Spruce Creek Golf Course"],
				["city" => "Timmins", "name" => "Spruce Needles Golf Club"],
				["city" => "Stouffville", "name" => "St. Andrew's East Golf & Country Club"],
				["city" => "Aurora", "name" => "St. Andrew's Valley Golf Club"],
				["city" => "St. Catherines", "name" => "St. Catharines Golf & Country Club"],
				["city" => "Mooretown", "name" => "St. Clair Parkway Golf Course"],
				["city" => "St. Davids", "name" => "St. Davids Golf Club"],
				["city" => "Etobicoke", "name" => "St. George's Golf and Country Club"],
				["city" => "St. Marys", "name" => "St. Marys Golf & Country Club"],
				["city" => "Union", "name" => "St. Thomas Golf & Country Club"],
				["city" => "Nolalu", "name" => "St. Urho's Golf Course & Driving Range"],
				["city" => "Port Rowan", "name" => "Starks Golf Course"],
				["city" => "Gormley", "name" => "Station Creek Golf Club"],
				["city" => "Ashton", "name" => "Stittsville Golf Course"],
				["city" => "Bowmanville", "name" => "Stonehenge Golf Club"],
				["city" => "Embro", "name" => "Stonehaven Golf Course"],
				["city" => "Nepean, Ottawa", "name" => "Stonebridge Golf Club"],
				["city" => "Sudbury", "name" => "Stonehill Golf Club"],
				["city" => "Elliot Lake", "name" => "Stone Ridge Golf Course"],
				["city" => "Owen Sound", "name" => "Stone Tree Golf and Fitness Club"],
				["city" => "Thunder Bay", "name" => "Strathcona Golf Course"],
				["city" => "Stratford", "name" => "Stratford County Club"],
				["city" => "Stratford", "name" => "Stratford Municipal Golf Course"],
				["city" => "Brampton", "name" => "Streetsville Glen Golf Club"],
				["city" => "Fenelon Falls", "name" => "Sturgeon Point Golf Club"],
				["city" => "Cornwall", "name" => "Summerheights Golf Links"],
				["city" => "Port Perry", "name" => "Summerlea Golf Club"],
				["city" => "Richmond Hill", "name" => "Summit Golf & Country Club"],
				["city" => "Brockville", "name" => "Sunnidell Golf"],
				["city" => "London", "name" => "Sunningdale Golf & Country Club"],
				["city" => "Port Perry", "name" => "Sunnybrae Golf Course"],
				["city" => "Sault Ste Marie", "name" => "Superior View Golf Course"],
				["city" => "Sundridge", "name" => "The Ridge Golf Club"],
				["city" => "Essex", "name" => "Sutton Creek Golf & Country Club"],
				["city" => "Gravenhurst", "name" => "Taboo Muskoka Resort & Golf"],
				["city" => "Wheatley", "name" => "Talbot Trail Golf Club"],
				["city" => "Grey Highlands", "name" => "Talisman Mountain Resort"],
				["city" => "Toronto", "name" => "Tam O'Shanter Golf Course"],
				["city" => "Ennismore", "name" => "Tamarac Golf & Country Club"],
				["city" => "Putnam", "name" => "Tamarack Ridge Golf Club"],
				["city" => "Thornton", "name" => "Tangle Creek Golf Club"],
				["city" => "Springfield", "name" => "Tarandowah Golfers Club"],
				["city" => "Tavistock", "name" => "Tavistock Golf Course"],
				["city" => "Tecumseh", "name" => "Tecumseh Golf Centre"],
				["city" => "London", "name" => "Thames Valley Golf Course"],
				["city" => "Thornhill", "name" => "The Thornhill Club"],
				["city" => "Thunder Bay", "name" => "Thunder Bay Country Club Ltd."],
				["city" => "Kanata, Ottawa", "name" => "Thunderbird Golf Club"],
				["city" => "Niagara Falls", "name" => "Thundering Waters Golf Club"],
				["city" => "Lake Shore", "name" => "Tilbury Golf Club"],
				["city" => "Tillsonburg", "name" => "Tillsonview Fairways"],
				["city" => "Brighton", "name" => "Timber Ridge Golf Course"],
				["city" => "Lanark", "name" => "Timber Run Golf & Country Club"],
				["city" => "Garson", "name" => "Timberwolf Golf Club"],
				["city" => "Brockville", "name" => "Tincap Golf Club"],
				["city" => "Toronto", "name" => "Toronto Golf Club"],
				["city" => "Toronto", "name" => "Toronto Hunt Club"],
				["city" => "Markdale", "name" => "Townsend Lake Golf & Country Club"],
				["city" => "Milton", "name" => "Trafalgar Golf and Country Club"],
				["city" => "Hawkestone", "name" => "Trehaven Golf & Country Club"],
				["city" => "Trenton", "name" => "Trenton Golf Club"],
				["city" => "Corbyville", "name" => "Trillium Wood Golf Club"],
				["city" => "Turkey Point", "name" => "Turkey Point Provincial Park Golf Course"],
				["city" => "Brampton", "name" => "Turnberry Golf Club"],
				["city" => "Campbellville", "name" => "Turtle Creek Golf Club"],
				["city" => "Vineland", "name" => "Twenty Valley Golf and Country Club"],
				["city" => "Wasaga Beach", "name" => "Twin Creeks Golf and Country Club"],
				["city" => "Coniston", "name" => "Twin Stacks Golf Club"],
				["city" => "Delaware", "name" => "Twin Streams Golf Course"],
				["city" => "Burlington", "name" => "Tyandaga Golf Course"],
				["city" => "", "name" => "Unionville Golf Centre"],
				["city" => "Thornhill", "name" => "Uplands Golf & Ski Club"],
				["city" => "Morrisburg", "name" => "Upper Canada Golf Course"],
				["city" => "Markham", "name" => "Upper Unionville Golf Club"],
				["city" => "Verner", "name" => "Verner Municipal Golf Course"],
				["city" => "Minesing", "name" => "Vespra Hills Golf Club"],
				["city" => "Guelph", "name" => "Victoria Park East Golf Club"],
				["city" => "Alban", "name" => "Voyageur Golf Course"],
				["city" => "Walkerton", "name" => "Walkerton Golf & Curling Club"],
				["city" => "Wardsville", "name" => "Wardsville Golf Club"],
				["city" => "Warkworth", "name" => "Warkworth Golf Club"],
				["city" => "Wainfleet", "name" => "Water Park Golf & Country Club"],
				["city" => "Waterloo", "name" => "Waterloo Golf Academy"],
				["city" => "Pickering", "name" => "Watson's Glen Golf Club"],
				["city" => "Wellington", "name" => "Wellington on the Lake Golf Course"],
				["city" => "London", "name" => "West Haven Golf & Country Club"],
				["city" => "Madoc", "name" => "West Highland Golf Course"],
				["city" => "Westbrook", "name" => "Westbrook Golf Club"],
				["city" => "London", "name" => "Westminster Trails Golf Club"],
				["city" => "Kitchener", "name" => "Westmount Golf and Country Club"],
				["city" => "Bolsover", "name" => "Western Trent Golf Club"],
				["city" => "Toronto", "name" => "Weston Golf and Country Club"],
				["city" => "Aurora", "name" => "Westview Golf Club"],
				["city" => "Niagara Falls", "name" => "Whirlpool Golf Course"],
				["city" => "Sioux Narrows", "name" => "White Moose Resort & Golf Course"],
				["city" => "Whitevale", "name" => "Whitevale Golf Club"],
				["city" => "Port Colborne", "name" => "Whisky Run Golf Club"],
				["city" => "Hanover", "name" => "Whispering Hills Golf Club"],
				["city" => "Cambridge", "name" => "Whistle Bear Golf Club"],
				["city" => "Sioux Narrows", "name" => "White Moose Resort & Golf Club"],
				["city" => "Orleans", "name" => "White Sands Golf Course & Practice Centre"],
				["city" => "Eganville", "name" => "Whitetail Golf Club"],
				["city" => "Thunder Bay", "name" => "Whitewater Golf Club"],
				["city" => "Georgian Bluffs", "name" => "Wiarton Golf Club"],
				["city" => "Thedford", "name" => "Widder Station Golf & Country Club Inc."],
				["city" => "Douro-Dummer", "name" => "Wildfire Golf Club"],
				["city" => "Essex", "name" => "Wildwood Golf Course & RV Resort"],
				["city" => "Thornton", "name" => "The Wilds at Cedar Valley Golf Course"],
				["city" => "Wellington", "name" => "Wildwinds Golf Links"],
				["city" => "Niagara Falls", "name" => "Willodell Golf Club of Niagara"],
				["city" => "London", "name" => "The Willow's Golf & Country Club"],
				["city" => "Orillia", "name" => "Willow Creek"],
				["city" => "Essex", "name" => "Willow Creek Golf Club"],
				["city" => "Sutton", "name" => "Willow Greens Golf Club"],
				["city" => "Blenheim", "name" => "Willow Ridge Golf & Country Club"],
				["city" => "Mount Hope, Hamilton", "name" => "Willow Valley Golf Course"],
				["city" => "Newcastle", "name" => "Wilmot Creek Golf Course"],
				["city" => "Whitby", "name" => "Winchester Golf Club"],
				["city" => "Windermere", "name" => "Windermere Golf & Country Club"],
				["city" => "Wingham", "name" => "Wingham Golf Club & Curling Club"],
				["city" => "Wolfe Island", "name" => "Wolfe Island Riverfront Golf Course"],
				["city" => "Killaloe", "name" => "Wolf Ridge Golf Club"],
				["city" => "Janetville", "name" => "Wolf Run Golf Club"],
				["city" => "Uxbridge", "name" => "Wooden Sticks Golf Course"],
				["city" => "Woodslee", "name" => "Woodland Hills Golf Club"],
				["city" => "Clinton", "name" => "Woodlands Links Golf Club"],
				["city" => "Tottenham", "name" => "Woodington Lake Golf Club"],
				["city" => "Simcoe", "name" => "Woodside Greens Golf Club"],
				["city" => "Woodstock", "name" => "Woodstock Meadows Golf Club"],
				["city" => "Woodview", "name" => "Woodview Golf"],
				["city" => "Milton", "name" => "Wyldewood Golf & Country Club"],
				["city" => "Uxbridge", "name" => "Wyndance Golf Club"],
				["city" => "", "name" => "York Downs Golf & Country Club"]

			);

		}
}
