/**
 * auth.js
 */
export const SET_USER = 'SET_USER'
export const LOGOUT = 'LOGOUT'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const SET_TOKEN = 'SET_TOKEN'

export const SET_COURSE = 'SET_COURSE'
export const FETCH_COURSE_FAILURE = 'FETCH_COURSE_FAILURE'

export const SET_PLAYER_DATA = 'SET_PLAYER_DATA'
export const SET_PLAYER_COURSE_DATA = 'SET_PLAYER_COURSE_DATA'
export const SET_PLAYER_ID = 'SET_PLAYER_ID'
export const SET_PLAYER_DATA = 'SET_PLAYER_DATA'

export const FETCH_PLAYER_FAILURE = 'FETCH_PLAYER_FAILURE'
export const SET_PLAYER_STATUS = 'SET_PLAYER_STATUS'
export const SET_PLAYER_COURSE_ID = 'SET_PLAYER_COURSE_ID'
export const PLAYER_LOGOUT = 'PLAYER_LOGOUT'
